baseURL = "https://www.florian-schuessel.de/"
languageCode = "en-us"
title = "Flo Schüssel - Software consultant & developer"

theme = "flow-shizzle"

enableGitInfo = true

[params]
  avatar = "/images/me/avatar.png"

  [params.social]
    GitHub = "scflode"
    Twitter = "scflode"
    Email   = "mail@florian-schuessel.de"
    Gitlab = "scflode"
    Bitbucket = "scflode"
    Xing = "Florian_Schuessel"
