baseURL = "https://www.florian-schuessel.de/"
languageCode = "en-us"
title = "Software consulting & development"

theme = "flow-shizzle"

enableGitInfo = true

[params]
  subTitle = "Florian Schüssel"
  avatar = "/images/me/avatar.png"
