[build]
base = "/"
publish = "public"
command = "npm install -g postcss-cli autoprefixer && hugo --gc --minify"

[context.production]
command = "npm install -g postcss-cli autoprefixer && hugo --gc --minify --enableGitInfo"

[context.production.environment]
HUGO_VERSION = "0.57.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "npm install -g postcss-cli autoprefixer && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.57.2"

[context.branch-deploy]
command = "npm install -g postcss-cli autoprefixer && hugo --gc --minify -b $DEPLOY_PRIME_URL"

