backend:
  name: git-gateway
  branch: production
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "tweet"
    label: "Tweet"
    folder: "content/posts/tweets"
    create: true
    slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "hidden", default: "Tweet"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "categories", widget: "list", allow_add: false, default: ["shorts"]}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "string"}
  - name: "post"
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", required: false, default: true}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Categories", name: "categories", widget: "list", default: ["longs"]}
      - {label: "Body", name: "body", widget: "markdown"}
